export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const UPDATE_LOGIN_STATUS = "UPDATE_LOGIN_STATUS";
export const SET_USER_ID = "SET_USER_ID";

export const UPDATE_CURRENT_PRICES = "UPDATE_CURRENT_PRICES";
export const SET_CURRENT_PRICES = "SET_CURRENT_PRICES";
