export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const UPDATE_LOGIN_STATUS = "UPDATE_LOGIN_STATUS";
export const SET_USER_ID = "SET_USER_ID";

export const UPDATE_PRICES = "UPDATE_PRICES";
export const SET_PRICES = "SET_PRICES";
export const GET_COINS = "GET_COINS";
export const SET_COINS = "SET_COINS";
export const SET_COINS_REQUEST_ERROR = "SET_COINs_REQUEST_ERROR";
