export const SET_LOGIN_STATUS = "SET_LOGIN_STATUS";
export const UPDATE_LOGIN_STATUS = "UPDATE_LOGIN_STATUS";
export const SET_USER_ID = "SET_USER_ID";

// COINS REDUCER
export const GET_COIN_PRICES = "GET_COIN_PRICES";
export const SET_PRICES = "SET_PRICES";
export const GET_COIN_NAMES = "GET_COIN_NAMES";
export const SET_COIN_NAMES = "SET_COIN_NAMES";
export const SET_COINS_REQUEST_ERROR = "SET_COINS_REQUEST_ERROR";
export const ASSEMBLE_COINS = "ASSEMBLE_COINS";
export const GET_COIN_STATS = "GET_COIN_STATS";
export const SET_COIN_STATS = "SET_COIN_STATS";
